fix(#1847): documentation - add keypress to props for input(textfield)
GovAlta/ui-components-docs pull request #184
Opened 2024-06-20 16:31 UTC by syedszeeshan

AFTER:

React
![image](https://github.com/GovAlta/ui-components-docs/assets/47701214/f0dbeb19-5d96-4494-93cc-fa276a3a8953)

Angular
![image](https://github.com/GovAlta/ui-components-docs/assets/47701214/76dfb6b0-5d5a-4253-bb49-301d6c539675)

2024-06-21 22:36 UTC, lizhuomeng71 commented
issue is verified for react and angular

2024-06-24 17:14 UTC, chrisolsen approved these changes

2024-06-24 17:15 UTC, chrisolsen commented on src/routes/components/TextField.tsx
> +      type: "(name: string, value: string | Date | number) => void",
Textarea does have a `Date` type

2024-06-24 17:16 UTC, chrisolsen requested changes

2024-06-24 17:16 UTC, chrisolsen commented on src/routes/components/TextField.tsx
> +      type: "(name: string, value: string | Date | number) => void",
Textarea does have a Date type

2024-06-24 17:28 UTC, chrisolsen approved these changes

2024-06-24 19:56 UTC, merged